{{- if and .Values.dataPlane.enabled .Values.dataPlane.edge.tls.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "dataPlane.edge.tlsSecretName is required when creating its Secret" .Values.dataPlane.edge.tlsSecretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "dataPlane.edge.tls.cert is required" .Values.dataPlane.edge.tls.cert | b64enc | quote }}
  tls.key: {{ required "dataPlane.edge.tls.key is required" .Values.dataPlane.edge.tls.key | b64enc | quote }}
{{- end }}
