{{- if or .Values.monitoring.prometheusEndpoint .Values.monitoring.lokiEndpoint .Values.monitoring.tempoEndpoint }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: akernel-otel-collector-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: akernel
    component: otel-collector
data:
  otel_config.yaml: |
{{ .Files.Get "files/otel-collector/config.yaml" | indent 4 }}
  control.yaml: |
{{ .Files.Get "files/otel-collector/control.yaml" | indent 4 }}
{{- end }}
