{{- if .Values.traefik.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: {{ .Release.Namespace }}
  {{- with .Values.traefik.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.traefik.service.type }}
  {{- with .Values.traefik.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- if and (eq .Values.traefik.service.type "LoadBalancer") .Values.traefik.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.traefik.service.loadBalancerIP | quote }}
  {{- end }}
  ports:
    - name: websecure
      port: {{ .Values.traefik.ports.websecure }}
      targetPort: websecure
    - name: web
      port: {{ .Values.traefik.ports.web }}
      targetPort: web
    {{- if ne .Values.traefik.service.type "LoadBalancer" }}
    - name: dashboard
      port: {{ .Values.traefik.ports.dashboard }}
      targetPort: dashboard
    {{- end }}
  selector:
    app: traefik
{{- end }}
